### ISSUE TITLE
Can't have 2 different values for JS indent level and JSON indent level

### ISSUE THREAD

**Issue by angrybacon** [json-emacs/json-mode#32]
[One month ago](https://github.com/joshwnj/json-mode/commit/c3be51fc8ad520aec47be755aec8efe303bfd448), you made a change that basically forbids me to have 4-spaces indenting with js-mode and 2-spaces indenting with json-mode.

**Comment by angrybakon** [comment]
Has anyone acknowledged this issue?

**Comment by joshwnj** [comment]
Sorry for the delay @angrybakon, this one slipped my radar. I'd like to figure out a good solution here. Do you think it would work well if we:

- add a new `json-indent-level`, which is `nil` by default
- when `json-indent-level` has a value we use it
- otherwise we use `js-indent-level`

Would that solve your case?

**Comment by angrybakon** [comment]
Yup, perfectly fine to me. Thank you :)

**Comment by taku0** [comment]
This would solve this.

```elisp
(add-hook 'json-mode-hook (lambda () (setq-local js-indent-level 2)))
```
